version: '3.3'

services:
  hello-world-api:
    container_name: hello-world
    build:
        context: .
        dockerfile: Dockerfile
        args:
            - NODE_ENV
    command: ["npm", "run", "watch"]
    ports:
      - "3000:3000"
    volumes:
      - ./index.js:/app/index.js
      - /app/node_modules
